language: python
sudo: disabled

python:
  - "2.7"

branches:
  - feature/lm_tests

os:
  - linux
  
git:
  depth: 1

env:
  global:
    - LOC=/home/travis/virtualenv/python2.7  # Location where VE is created on travis
    - CMD1="coverage run --source $LOC/lib/python2.7/site-packages/radical/pilot/agent/lm/ -m pytest -vvv tests/;flake8 tests/;pylint tests/"
    - CMD2="flake8 --config=.flake8 $LOC/lib/python2.7/site-packages/radical/pilot/agent/lm/"
    - CMD3="pylint $LOC/lib/python2.7/site-packages/radical/pilot/agent/lm/"
    - MAIN_CMD=$CMD1
    - COVERAGE=false
  matrix:
    - MAIN_CMD=$CMD1 COVERAGE=true
    - MAIN_CMD=$CMD2
    - MAIN_CMD=$CMD3
  
# command to install dependencies
install:
  - pip install .
  - pip install coverage
  - pip install flake8
  - pip install pylint
  - pip install codecov

   
script:
  #- coverage run --source $LOC/lib/python2.7/site-packages/radical/pilot/agent/lm/ -m pytest -vvv tests/;
  #- flake8 tests/;
  #- pylint tests/
  #- flake8 --config=.flake8 $LOC/lib/python2.7/site-packages/radical/pilot/agent/lm/
  #- pylint $LOC/lib/python2.7/site-packages/radical/pilot/agent/lm/
  - echo $MAIN_CMD
  - eval $MAIN_CMD
  
after_success:
   - if [[ $COVERAGE == 'true' ]]; then \
       coverage combine; \
       coverage xml; \
       coverage report;\
     fi
